name: stepup
description: An app build with the stacked framework
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^3.1.0+3
  stacked_services: ^0.9.9
  pedometer: ^3.0.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.17
  flutter_background_service: ^2.4.6
  flutter_local_notifications: ^13.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  stacked_generator: ^0.8.5
  change_app_package_name: ^1.1.0
  mockito: ^5.3.2
flutter:
  uses-material-design: true